apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: app-container
        image: gcr.io/moelzedy/gcrproject2:latest
        ports:
        - containersPort: 5000
        env:
          - name: PORT
            value: "5000"