apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: app-container
        image: gcr.io/moelzedy/gcrproject2-dev:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"

---
kind: Service
apiVersion: v1
metadata:
  name:  python-app-service
  namespace: gcp-project2-dev
spec:
  selector:
    app: python
  type:  LoadBalancer
  ports:
  - protocol: "TCP"
    port:  80
    targetPort:  5000

