steps:

  # build the container image
- name: 'build'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcrproject2', '.']

  # push the container image
- name : 'push'
  args: ['push', 'gcr.io/$PROJECT_ID/gcrproject2']

  # deploy the container image to GKE
- name: 'deploy'
  args:
    - run
    - --filename=app-deployment.yml
    - --image=gcr.io/$PROJECT_ID/gcrproject2
    - --location=us-central1-c
    - --cluster=project2-cluster
    - --namespace=gcp-project2
